development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: nestfinder_development
  logging: true

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: nestfinder_production
